### ISSUE TITLE
iPad Air 9.0.2 crash

### ISSUE THREAD

**Issue by D0m0** [Siguza/ios-kern-utils#11]
I'm not sure if I'm doing it right, but my iPad Air (J72AP_13A452) crashes when using any utility except kmap, while ./cl0ver and ./cl0ver dump both work OK.

Kernel panic log attached.
[panic-2017-05-14-141930_part.ips.txt](https://github.com/Siguza/ios-kern-utils/files/999417/panic-2017-05-14-141930_part.ips.txt)

**Comment by Siguza** [comment]
I see from the panic log that you were using `kmem`... accessing unmapped memory in kernel mode causes a panic, and `kmem` is the tool that gives you exactly that kind of control.  
I can further see that you were trying to access `0xffffff827fef8000`, which on my device is a 1MB NULL mapping, i.e. exactly the kind of mapping that will cause a panic if accessed.

**Comment by D0m0** [comment]
Thanks for the quick reply! Yeah, the last panic was from kmem, that address I got from kmap which I ran previously. But kdump should still work, anyway? Here's a panic log from kdump: 
[panic-2017-05-14-141447_part.ips.txt](https://github.com/Siguza/ios-kern-utils/files/1001975/panic-2017-05-14-141447_part.ips.txt)

**Comment by D0m0** [comment]
P.S. kmem works! I actually did access a NUL mapping ;)

**Comment by D0m0** [comment]
When I search for the kernel in kmap output, it is consistent with what "cl0ver slide" says about the kernel slide. But it reports that region as nul, i.e.:

`ffffff801c800000-ffffff811f000000 [ 4136M] ----/---- [mem nul cp] 0000000000000000 [0 0 0 0 0] 00000000/00000000:<         0> 0,0 {0,0}`

**Comment by Siguza** [comment]
Well, on iOS 9 on later that depends. It _can_ be the same, but the null mapping can also start earlier, which is what broke practically all kernel utilities.  
I still haven't come up with a definitive fix for that, but I do have a new idea that I plan to try out in a few days.

**Comment by D0m0** [comment]
Yes, it seems to start a little earlier indeed. But I still can't read the memory that I "should" be able to. I hope you come up with something!

**Comment by Siguza** [comment]
Should be fixed with 026081c7b5f897d7ec3d14be827c5fc9b7890f4b.
