### ISSUE TITLE
Pangu 7.1.x Compatibility

### ISSUE THREAD

**Issue by deepfriedfilth** [Siguza/ios-kern-utils#12]
Could you update the readme to reflect compatibility with Pangu 7.1.x JB?

tfp0 is enabled in the latest version of their untether package (v0.3) and in their desktop app since v1.2.0

(Also, thanks for this fork, which allowed me to update my 5S from 7.1.2 to 10.2 via setting my boot-nonce with the included nvpatch tool)

**Comment by Siguza** [comment]
Done. :)
