### ISSUE TITLE
kdump [!] Failed to locate kernel

### ISSUE THREAD

**Issue by malhal** [Siguza/ios-kern-utils#21]
```
iPad:~ root# kdump
[!] Failed to locate kernel
```

kern-utils-utils 1.4.1-1
iOS 13.4.1
iPad 9.7" Pro

**Comment by Siguza** [comment]
Why would you even want that?

**Comment by DumbGameMaker** [comment]
I get the error when running `nvpatch com.apple.system.boot-nonce` on my SE when trying to downgrade 13.6 to 13.5

**Comment by Siguza** [comment]
The method `nvpatch` uses has been fixed back in iOS 11.  
And `kdump` has been unnecessary since iOS 10.

I'm closing this.
