### ISSUE TITLE
[!] Failed to get kernel task

### ISSUE THREAD

**Issue by leandroprz** [Siguza/ios-kern-utils#3]
I just used cl0ver to patch my device and got the message `[*] Successfully installed patch`, but wanted to make sure the process was successful with this tool as well. I tried with `./kmap` and I'm getting this error:

> 6S:/private/var/root/sarasa root# ./kmap
> [!] Failed to get kernel task
> 6S:/private/var/root/sarasa root#

**Comment by Siguza** [comment]
Could you try running

    ./kdump -v -d

And post its output?

**Comment by leandroprz** [comment]
Sorry, I can no longer test it with the same setup because yesterday I updated my phone to 10.2. It seems cl0ver worked fine, but this tool didn't.

**Comment by Siguza** [comment]
Okay, that seems weird... but oh well.
