### ISSUE TITLE
Kernel Panic

### ISSUE THREAD

**Issue by CrypticGit** [Siguza/ios-kern-utils#4]
I ran kdump and the kernel paniced but the wierd thing was i still have my themed status bar from anenome and i cant get rid of it Ive tried hardreseting, dfumode, recov mode. Is this my phone or this tool?

**Comment by Siguza** [comment]
[I'm pretty sure that's anemone](https://twitter.com/coolstarorg/status/831310923298021377).

Also, are you on iOS 10?

**Comment by CrypticGit** [comment]
@Siguza Ok Thanks and yes i'm on 10.2
