### ISSUE TITLE
Are the commands eventually going to work?

### ISSUE THREAD

**Issue by CrypticGit** [Siguza/ios-kern-utils#5]
I keep trying and it just panics. Does it log the kernel to a file?

**Comment by Siguza** [comment]
Okay, so:

- You're on iOS 10, so if your goal is to get a kernel dump, you can get a much cleaner one (even symbolicated!) directly from the IPSW, as they're not unencrypted.
- Yes, the kernel wouldbe written to `./kernel.bin`.
- The current release does not support iOS 10, see #2.
