### ISSUE TITLE
Question about kernel task

### ISSUE THREAD

**Issue by CrypticGit** [Siguza/ios-kern-utils#6]
From what iv'e heard, finding the port can be a major security issue when applied to your device so is their a benefit to finding the port?

**Comment by Siguza** [comment]
- "Finding the port"? You don't "find", you just... fetch it.  
- Security issues? It's only ever available to root. Do untrusted parties have root access to your device?
- tfp0 is something your jailbreak installs, kern-utils merely uses it.
- "Is there a benefit to it"? Imagine a room. Is there a benefit to having a door? Yeah, you can get in now.
